# Generated by Django 2.1.1 on 2018-12-02 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_app', '0003_auto_20181128_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='friendrelationship',
            name='friend',
            field=models.ForeignKey(on_delete='cascade', related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrelationship',
            name='user',
            field=models.ForeignKey(on_delete='cascade', related_name='userCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
