# Generated by Django 2.1.1 on 2018-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_app', '0004_auto_20181202_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
