# Generated by Django 2.1.1 on 2018-12-04 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_app', '0005_auto_20181202_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete='cascade', related_name='userInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
