# Generated by Django 2.1.3 on 2019-01-21 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BetCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameCode', models.TextField(max_length=500, unique=True)),
                ('state', models.BooleanField(default=False)),
                ('openDate', models.DateField()),
                ('endDate', models.DateField()),
                ('max_users', models.IntegerField(null=True)),
                ('name', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=900, null=True)),
                ('image', models.ImageField(default='category_pics/None/no-img.jpg', upload_to='category_pics/')),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet', to='betcroquet_app.Bet')),
                ('betCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betCollCategory', to='betcroquet_app.BetCollection')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcroquet_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=900, null=True)),
                ('image', models.ImageField(default='option_pics/None/no-img.jpg', upload_to='option_pics/')),
                ('video', models.TextField(max_length=900, null=True)),
                ('category', models.ManyToManyField(related_name='optionCategory', to='betcroquet_app.Category')),
            ],
        ),
        migrations.AddField(
            model_name='categorywinner',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betcroquet_app.Option'),
        ),
        migrations.AddField(
            model_name='bet',
            name='betCollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betCollBet', to='betcroquet_app.BetCollection'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
