# Generated by Django 2.1.3 on 2019-01-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcroquet_app', '0002_auto_20190121_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='betcollection',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betcollection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
