# Generated by Django 2.1.3 on 2019-01-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betcroquet_app', '0004_auto_20190121_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BetSelect',
            new_name='BetSelection',
        ),
    ]
