# Generated by Django 2.1.3 on 2019-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcroquet_app', '0006_auto_20190121_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='betcollection',
            name='image',
            field=models.ImageField(default='defaul.jpg', upload_to='bet_templates/'),
        ),
    ]
