# Generated by Django 2.1.3 on 2019-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcroquet_app', '0007_betcollection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betcollection',
            name='image',
        ),
        migrations.AddField(
            model_name='bettemplate',
            name='image',
            field=models.ImageField(default='defaul.jpg', upload_to='bet_templates/'),
        ),
    ]
