# Generated by Django 2.1.3 on 2019-01-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcroquet_app', '0008_auto_20190123_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettemplate',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='bet_templates/'),
        ),
    ]
